server.port: ${PORT}
spring:
    profiles.active: ${APP_PROFILE}
    datasource:
      url: jdbc:h2:./simplecrud
      username: simplecrud
      password: simplecrud
      driver-class-name: org.h2.Driver
      initialization-mode: always

vars:
  openshift: maneiro
  message: Mas para onde vai o mundo?

h2.implicitRelativePath: true